--------------------------- 3D HPS estimation ---------------------------
['/home/pranoy/code/auto-transform/new_data/smpl_params/image19.jpg.pkl'
 '/home/pranoy/code/auto-transform/new_data/smpl_params/image25.jpg.pkl'
 '/home/pranoy/code/auto-transform/new_data/smpl_params/image14.jpg.pkl'
 '/home/pranoy/code/auto-transform/new_data/smpl_params/image11.jpg.pkl'
 '/home/pranoy/code/auto-transform/new_data/smpl_params/image36.jpg.pkl']
train_list 39
test_list 5
Epoch: [0][1/2]	Time  9.167 ( 9.167)	Data  0.000 ( 0.000)	Loss 1.9555 (1.9555)
epoch: 0 train_loss: 1.895 val_loss: 2.096
Epoch: [1][1/2]	Time  7.930 ( 7.930)	Data  0.000 ( 0.000)	Loss 1.7311 (1.7311)
epoch: 1 train_loss: 1.702 val_loss: 2.046
Epoch: [2][1/2]	Time  8.002 ( 8.002)	Data  0.000 ( 0.000)	Loss 1.5528 (1.5528)
epoch: 2 train_loss: 1.524 val_loss: 1.965
Epoch: [3][1/2]	Time  8.203 ( 8.203)	Data  0.000 ( 0.000)	Loss 1.4126 (1.4126)
epoch: 3 train_loss: 1.389 val_loss: 1.867
Epoch: [4][1/2]	Time  8.038 ( 8.038)	Data  0.000 ( 0.000)	Loss 1.2843 (1.2843)
epoch: 4 train_loss: 1.275 val_loss: 1.758
Epoch: [5][1/2]	Time  7.997 ( 7.997)	Data  0.000 ( 0.000)	Loss 1.1709 (1.1709)
epoch: 5 train_loss: 1.166 val_loss: 1.646
Epoch: [6][1/2]	Time  7.948 ( 7.948)	Data  0.000 ( 0.000)	Loss 1.1147 (1.1147)
epoch: 6 train_loss: 1.098 val_loss: 1.535
Epoch: [7][1/2]	Time  7.976 ( 7.976)	Data  0.000 ( 0.000)	Loss 1.0212 (1.0212)
epoch: 7 train_loss: 1.073 val_loss: 1.439
Epoch: [8][1/2]	Time  7.929 ( 7.929)	Data  0.000 ( 0.000)	Loss 0.9968 (0.9968)
epoch: 8 train_loss: 1.027 val_loss: 1.382
Epoch: [9][1/2]	Time  8.023 ( 8.023)	Data  0.000 ( 0.000)	Loss 0.9775 (0.9775)
epoch: 9 train_loss: 0.982 val_loss: 1.348
Epoch: [10][1/2]	Time  7.923 ( 7.923)	Data  0.000 ( 0.000)	Loss 0.9871 (0.9871)
epoch: 10 train_loss: 0.970 val_loss: 1.314
Epoch: [11][1/2]	Time  7.955 ( 7.955)	Data  0.000 ( 0.000)	Loss 0.8911 (0.8911)
epoch: 11 train_loss: 0.915 val_loss: 1.271
Epoch: [12][1/2]	Time  7.923 ( 7.923)	Data  0.000 ( 0.000)	Loss 0.8767 (0.8767)
epoch: 12 train_loss: 0.881 val_loss: 1.235
Epoch: [13][1/2]	Time  7.977 ( 7.977)	Data  0.000 ( 0.000)	Loss 0.8311 (0.8311)
epoch: 13 train_loss: 0.839 val_loss: 1.198
Epoch: [14][1/2]	Time  8.070 ( 8.070)	Data  0.000 ( 0.000)	Loss 0.8111 (0.8111)
epoch: 14 train_loss: 0.829 val_loss: 1.156
Epoch: [15][1/2]	Time  8.020 ( 8.020)	Data  0.000 ( 0.000)	Loss 0.7606 (0.7606)
epoch: 15 train_loss: 0.834 val_loss: 1.124
Epoch: [16][1/2]	Time  7.975 ( 7.975)	Data  0.000 ( 0.000)	Loss 0.7409 (0.7409)
epoch: 16 train_loss: 0.765 val_loss: 1.108
Epoch: [17][1/2]	Time  8.056 ( 8.056)	Data  0.000 ( 0.000)	Loss 0.7534 (0.7534)
epoch: 17 train_loss: 0.761 val_loss: 1.080
Epoch: [18][1/2]	Time  8.065 ( 8.065)	Data  0.000 ( 0.000)	Loss 0.7221 (0.7221)
epoch: 18 train_loss: 0.716 val_loss: 0.989
Epoch: [19][1/2]	Time  7.946 ( 7.946)	Data  0.000 ( 0.000)	Loss 0.6709 (0.6709)
epoch: 19 train_loss: 0.673 val_loss: 0.870
Epoch: [20][1/2]	Time  7.899 ( 7.899)	Data  0.000 ( 0.000)	Loss 0.6611 (0.6611)
epoch: 20 train_loss: 0.649 val_loss: 0.772
Epoch: [21][1/2]	Time  7.945 ( 7.945)	Data  0.000 ( 0.000)	Loss 0.6321 (0.6321)
epoch: 21 train_loss: 0.620 val_loss: 0.685
Epoch: [22][1/2]	Time  7.886 ( 7.886)	Data  0.000 ( 0.000)	Loss 0.6386 (0.6386)
epoch: 22 train_loss: 0.608 val_loss: 0.617
Traceback (most recent call last):
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/pose_2D.py", line 25, in detect_pose
    results = holistic.process(image)
  File "/home/pranoy/.local/lib/python3.8/site-packages/mediapipe/python/solutions/holistic.py", line 160, in process
    results = super().process(input_data={'image': image})
  File "/home/pranoy/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 366, in process
    self._graph.wait_until_idle()
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 362, in <module>
    args = parser.parse_args()
  File "main.py", line 326, in main_worker
    # train for one epoch
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/train.py", line 54, in train_epoch
    for i, (batch) in enumerate(train_loader):
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/dataset.py", line 92, in __getitem__
    mediapipe_results = detect_pose(img)# shape (18, 2)
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/pose_2D.py", line 42, in detect_pose
    results_mediapipe["normalised_keypoints"] = normalised_keypoints
  File "/home/pranoy/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 626, in __exit__
    self.close()
  File "/home/pranoy/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 384, in close
    self._graph.close()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/pose_2D.py", line 25, in detect_pose
    results = holistic.process(image)
  File "/home/pranoy/.local/lib/python3.8/site-packages/mediapipe/python/solutions/holistic.py", line 160, in process
    results = super().process(input_data={'image': image})
  File "/home/pranoy/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 366, in process
    self._graph.wait_until_idle()
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 362, in <module>
    args = parser.parse_args()
  File "main.py", line 326, in main_worker
    # train for one epoch
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/train.py", line 54, in train_epoch
    for i, (batch) in enumerate(train_loader):
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/dataset.py", line 92, in __getitem__
    mediapipe_results = detect_pose(img)# shape (18, 2)
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/pose_2D.py", line 42, in detect_pose
    results_mediapipe["normalised_keypoints"] = normalised_keypoints
  File "/home/pranoy/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 626, in __exit__
    self.close()
  File "/home/pranoy/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 384, in close
    self._graph.close()
KeyboardInterrupt