2022-10-26 17:02:26,348 INFO    MainThread:1627102 [wandb_setup.py:_flush():76] Configure stats pid to 1627102
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_setup.py:_flush():76] Loading settings from /home/pranoy/.config/wandb/settings
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_setup.py:_flush():76] Loading settings from /home/pranoy/code/noah-research/CLIFF-pose-estimation/wandb/settings
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'main.py'}
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_init.py:_log_setup():461] Logging user logs to /home/pranoy/code/noah-research/CLIFF-pose-estimation/wandb/run-20221026_170226-ocbeo52v/logs/debug.log
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_init.py:_log_setup():462] Logging internal logs to /home/pranoy/code/noah-research/CLIFF-pose-estimation/wandb/run-20221026_170226-ocbeo52v/logs/debug-internal.log
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_init.py:init():495] calling init triggers
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_init.py:init():548] starting backend
2022-10-26 17:02:26,349 INFO    MainThread:1627102 [wandb_init.py:init():552] setting up manager
2022-10-26 17:02:26,350 INFO    MainThread:1627102 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-26 17:02:26,351 INFO    MainThread:1627102 [wandb_init.py:init():558] backend started and connected
2022-10-26 17:02:26,352 INFO    MainThread:1627102 [wandb_init.py:init():636] updated telemetry
2022-10-26 17:02:26,485 INFO    MainThread:1627102 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2022-10-26 17:02:29,500 WARNING MsgRouterThr:1627102 [router.py:message_loop():76] message_loop has been closed
2022-10-26 17:02:36,632 WARNING MainThread:1627102 [wandb_init.py:init():1064] interrupted
Traceback (most recent call last):
  File "/home/pranoy/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home/pranoy/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 670, in init
    run_result = backend.interface.communicate_run(
  File "/home/pranoy/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 223, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/pranoy/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 329, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/pranoy/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/pranoy/.local/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
