Traceback (most recent call last):
  File "main.py", line 369, in <module>
    main_worker(args)
  File "main.py", line 330, in main_worker
    avg_train_loss  = train_epoch(train_loader, model, criterion, optimizer, epoch, args)
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/train.py", line 54, in train_epoch
    for i, (batch) in enumerate(train_loader):
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/dataset.py", line 104, in __getitem__
    with open(self.image_list[index], 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 's_06_act_13_subact_01_ca_01_001543.jpg'
Traceback (most recent call last):
  File "main.py", line 369, in <module>
    main_worker(args)
  File "main.py", line 330, in main_worker
    avg_train_loss  = train_epoch(train_loader, model, criterion, optimizer, epoch, args)
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/train.py", line 54, in train_epoch
    for i, (batch) in enumerate(train_loader):
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pranoy/code/noah-research/CLIFF-pose-estimation/dataset.py", line 104, in __getitem__
    with open(self.image_list[index], 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 's_06_act_13_subact_01_ca_01_001543.jpg'
--------------------------- 3D HPS estimation ---------------------------
/media/pranoy/Pranoy/human3.6M/images/s_06_act_13_subact_01_ca_01/s_06_act_13_subact_01_ca_01_001543.jpg
/media/pranoy/Pranoy/human3.6M/smpl_params/s_06_act_13_subact_01_ca_01_001543.pkl